-- Blackjack persistence schema (H2). Applied on startup; CREATE IF NOT
-- EXISTS keeps reruns harmless.

CREATE TABLE IF NOT EXISTS players (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id BIGINT NOT NULL REFERENCES players(id),
    started_at TIMESTAMP NOT NULL,
    ended_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS rounds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL REFERENCES sessions(id),
    round_number INT NOT NULL,
    player_cards VARCHAR(200) NOT NULL,
    dealer_cards VARCHAR(200) NOT NULL,
    player_value INT NOT NULL,
    dealer_value INT NOT NULL,
    outcome VARCHAR(20) NOT NULL,
    bet INT NOT NULL DEFAULT 0,
    bankroll_change INT NOT NULL DEFAULT 0,
    bankroll_after INT NOT NULL DEFAULT 0,
    played_at TIMESTAMP NOT NULL
);

-- Upgrade path for databases created before betting existed.
ALTER TABLE rounds ADD COLUMN IF NOT EXISTS bet INT NOT NULL DEFAULT 0;
ALTER TABLE rounds ADD COLUMN IF NOT EXISTS bankroll_change INT NOT NULL DEFAULT 0;
ALTER TABLE rounds ADD COLUMN IF NOT EXISTS bankroll_after INT NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS round_actions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    round_id BIGINT NOT NULL REFERENCES rounds(id),
    seq INT NOT NULL,
    action VARCHAR(20) NOT NULL
);
